# Generated by Django 4.2 on 2024-11-10 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_created',
            new_name='created',
        ),
    ]
