# Generated by Django 4.2 on 2024-11-02 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_approved',
            field=models.BooleanField(choices=[(True, 'Approved'), (False, 'Denied')], default=True),
            preserve_default=False,
        ),
    ]
