# Generated by Django 4.2 on 2024-11-02 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_approved',
        ),
    ]
