# Generated by Django 4.2 on 2024-11-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_post_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_approved',
            field=models.IntegerField(choices=[(1, 'Approved'), (0, 'Denied')], default=2),
        ),
    ]
