# Generated by Django 4.2 on 2024-10-15 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'blank': 'Email cannot be empty.', 'null': 'Email cannot be empty.', 'unique': 'User with that email already exists.'}, max_length=254, unique=True),
        ),
    ]
